/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

//#import "NSColor.h"

@interface IBColor : NSColor
{
}

+ (void)setPreferredColor:(id)fp8 forName:(id)fp12;
+ (id)preferredColorForName:(id)fp8;
+ (id)bandSelectionBodyColor;
+ (id)viewSelectionColor;
+ (id)bandSelectionBorderColor;
+ (id)dragInsertionIndicatorColor;
+ (id)dragInsertionIndicatorFillColor;
+ (id)layoutRectColor;
+ (id)baselineColor;
+ (id)layoutInfoColor;
+ (id)boundsInfoColor;
+ (id)customViewColor;
+ (id)missingImageColor;
+ (id)connectionLineStrokeColor;
+ (id)connectionLineFillColor;
+ (id)connectionLineShadowColor;
+ (id)targetIdentifierColor;
+ (id)liveLayoutGuideColor;
+ (id)layoutGuideLabelFillColor;
+ (id)layoutGuideLabelFrameColor;
+ (id)notesBackgroundColor;
+ (id)paletteBackgroundColor;
+ (id)paletteTitleFillColor;
+ (id)paletteTitleColor;
+ (id)paletteTextColor;
+ (id)inspectorGearBackgroundColor;
+ (id)inspectorModeLightGradientColor;
+ (id)inspectorModeDarkGradientColor;
+ (id)inspectorSliceLightGradientColor;
+ (id)inspectorSliceDarkGradientColor;
+ (id)inspectorSliceBorderColor;
+ (id)inspectorSliceToneColor;
+ (id)inspectorModeSelectionToneColor;
+ (id)inspectorModePressedToneColor;
+ (id)inspectorModeSeparatorColor;
+ (id)slateScrollerBackgroundColor;
+ (id)slateScrollerKnobColor;
+ (id)slateScrollerTrackedKnobColor;
+ (id)slateScrollerTrackColor;
+ (id)slateScrollerButtonFillColor;
+ (id)slateScrollerButtonIconColor;
+ (id)slateScrollerButtonPressedIconColor;
+ (id)slateScrollerButtonDisabledIconColor;
+ (id)slateScrollerButtonDisabledFillColor;
+ (id)slateScrollerButtonPressedFillColor;
+ (id)connectionSliceTitleFillColor;
+ (id)menuDropTargetIndicatorColor;
+ (id)menuDarkDropTargetIndicatorColor;
+ (id)menuLightDropTargetIndicatorColor;
+ (id)slatePaletteButtonPressedColor;
+ (id)slateElementViewBackgroundColor;
+ (id)slateElementViewHighlightColor;
+ (id)slateElementViewPressedColor;
+ (id)slateElementViewSelectedColor;
+ (id)slateElementViewTextColor;
+ (id)slateLabelHighlightColor;
+ (id)paletteChooserOutlineColor;
+ (id)paletteChooserPressedColor;
+ (id)paletteChooserHighlightColor;
+ (id)containerCustomViewBackgroundColor;
+ (id)childlessCustomViewBackgroundColor;
+ (id)childlessCustomViewTextColor;
+ (id)containerCustomViewTextColor;
+ (id)customViewDarkTexturedBorderColor;
+ (id)customViewDarkBorderColor;
+ (id)customViewLightBorderColor;
+ (id)toolbarItemContainerFillColor;
+ (id)lightSpotlightColor;
+ (id)darkSpotlightColor;
+ (id)spotlightBorderColor;
+ (id)lightPurpleSpotlightColor;
+ (id)darkPurpleSpotlightColor;
+ (id)spotlightTextColor;
+ (id)lightestSlateColor;
+ (id)lighterSlateColor;
+ (id)lightSlateColor;
+ (id)slateColor;
+ (id)darkSlateColor;
+ (id)darkerSlateColor;
+ (id)darkestSlateColor;
+ (id)darkestSlateHUDBackgroundColor;
+ (id)darkerSlateHUDBackgroundColor;
+ (id)darkSlateHUDBackgroundColor;
+ (id)slateHUDBackgroundColor;
+ (id)lightSlateHUDBackgroundColor;
+ (id)slateWarningColor;
+ (id)darkSlateWarningColor;

@end

