/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <AppKit/NSWindow.h>

@interface NSWindow (NSTimeMachineSupport)
- (void)setTimeMachineDelegate:(id)fp8;
- (id)timeMachineDelegate;
- (void)setMovable:(BOOL)fp8;
- (BOOL)isMovable;
@end

